### ISSUE TITLE
LOVED the game!!!

### ISSUE THREAD

**Issue by inglesuniversal** [Th1nhNg0/tic-tac-toe-multiplayer#3]
The only downside is that I am new to node.js so I can't figure out how to install it on my server and access it without a port and using an ssl connection just like your demo on heroku.

Any links to learn how to do that which you can kindly share with me?

Thanks

**Comment by Th1nhNg0** [comment]
Thank you.
You can change the port to 80 or 8080 here: https://github.com/Th1nhNg0/tic-tac-toe-multiplayer/blob/31dd95db1b467e362e31a4a09aee389fe9507a21/server/index.js#L73
I'm host on heroku so it's did all the hard work for me :D
